@echo off
cd /d "%~dp0..\backend"
echo [KubeMind AI] Starting backend...
echo [KubeMind AI] Installing Python dependencies...
pip install -r requirements.txt -q
echo.
echo [KubeMind AI] Starting FastAPI server on port 8000...
python main.py
